import { mkdir, readFile, writeFile } from "node:fs/promises";
import sharp from "sharp";

const esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const DISPLAY={adobe:"Adobe",elevenlabs:"ElevenLabs",invideo:"InVideo",hostinger:"Hostinger","hostinger-horizons":"Hostinger Horizons",horizons:"Hostinger Horizons",semrush:"Semrush",surfer:"Surfer",canva:"Canva",heygen:"HeyGen",fliki:"Fliki",pictory:"Pictory",soundraw:"SOUNDRAW",adcreative:"AdCreative.ai"};
const displayName=v=>DISPLAY[String(v||"").toLowerCase()]||String(v||"");
const words=t=>String(t||"").split(/\s+/).filter(Boolean);
const wrap=(text,maxChars,maxLines=4)=>{const out=[],ws=words(text);let line="";for(const word of ws){const next=(line+" "+word).trim();if(line&&next.length>maxChars){out.push(line);line=word}else line=next}if(line)out.push(line);if(out.length<=maxLines)return out;const kept=out.slice(0,maxLines);kept[maxLines-1]=kept[maxLines-1].replace(/\s+\S*$/,"")+"…";return kept};
const fitHeadline=(text,portrait)=>{const width=portrait?860:1040,base=portrait?54:48,min=portrait?34:30;for(let size=base;size>=min;size-=2){const max=Math.max(12,Math.floor(width/(size*.56)));const lines=wrap(text,max,4);if(lines.length<=4&&lines.every(x=>x.length<=max))return {size,lines}}return {size:min,lines:wrap(text,Math.floor(width/(min*.56)),4)}};
const fitStoryHeadline=text=>{const width=900,base=60,min=38;for(let size=base;size>=min;size-=2){const max=Math.max(12,Math.floor(width/(size*.55)));const lines=wrap(text,max,4);if(lines.length<=4)return {size,lines}}return {size:min,lines:wrap(text,Math.floor(width/(min*.55)),4)}};
const cardPath=(date,storyId,format="landscape")=>"assets/social-cards/"+date+"/"+storyId.replace(/[^a-z0-9-]+/gi,"-").slice(0,80)+"-"+format;
const loadMedia=async value=>{const source=String(value||"");if(/^https?:\/\//i.test(source)){const response=await fetch(source,{headers:{"user-agent":"MahGPT-StoryCard/1.0","accept":"image/*"},signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error("Story media request failed: "+response.status);const type=response.headers.get("content-type")||"";if(!type.startsWith("image/"))throw new Error("Story media is not an image: "+type);return Buffer.from(await response.arrayBuffer())}if(!source)throw new Error("Story media source is empty");return readFile(source)};
export const inspectMedia=async value=>{const media=await loadMedia(value),meta=await sharp(media).rotate().metadata(),width=Number(meta.width)||0,height=Number(meta.height)||0,aspectRatio=width&&height?width/height:0;return {width,height,aspectRatio,instagramCompatible:aspectRatio>=0.8&&aspectRatio<=1.91}};
export { cardPath, fitHeadline };
export const createCard=async(post,date,format="landscape")=>{const portrait=format==="instagram",w=portrait?1080:1200,h=portrait?1350:675,fit=fitHeadline(post.headline,portrait),source=post.source_name||"News",partner=displayName(post.detected_partner),base=cardPath(date,post.headline,format),svgPath=base+".svg",pngPath=base+".png",logo=await readFile("assets/brand/mahgpt-logo.svg","base64"),logoHref="data:image/svg+xml;base64,"+logo,headlineY=portrait?300:250,lineGap=Math.round(fit.size*1.22),badgeY=portrait?700:470,headline=fit.lines.map((x,i)=>"<tspan x=\"80\" dy=\""+(i?lineGap:0)+"\">"+esc(x)+"</tspan>").join(""),badge=partner?"<rect x=\"80\" y=\""+badgeY+"\" width=\"240\" height=\"42\" rx=\"21\" fill=\"#38bdf8\"/><text x=\"200\" y=\""+(badgeY+28)+"\" text-anchor=\"middle\" fill=\"#0f172a\" font-family=\"Arial,sans-serif\" font-size=\"20\" font-weight=\"700\">"+esc(partner)+"</text>":"",svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><rect width="${w}" height="${h}" fill="#101827"/><rect x="54" y="38" width="190" height="72" rx="14" fill="#fff"/><image href="${logoHref}" x="66" y="44" width="166" height="60" preserveAspectRatio="xMidYMid meet"/><text x="${w-80}" y="82" text-anchor="end" fill="#93c5fd" font-family="Arial,sans-serif" font-size="24" font-weight="700" letter-spacing="3">AI NEWS</text><text x="80" y="${headlineY}" fill="white" font-family="Arial,sans-serif" font-size="${fit.size}" font-weight="700">${headline}</text>${badge}<text x="80" y="${h-76}" fill="#dbeafe" font-family="Arial,sans-serif" font-size="22">Source: ${esc(source)}</text><text x="${w-80}" y="${h-76}" text-anchor="end" fill="#dbeafe" font-family="Arial,sans-serif" font-size="22">www.mahgpt.com</text></svg>`;await mkdir(svgPath.slice(0,svgPath.lastIndexOf("/")),{recursive:true});await writeFile(svgPath,svg);await sharp(Buffer.from(svg)).png().toFile(pngPath);return pngPath};
export const createStoryCard=async(post,date,feedMedia)=>{const w=1080,h=1920,media=await loadMedia(feedMedia),fit=fitStoryHeadline(post.headline),base=cardPath(date,post.story_id||post.headline,"story"),pngPath=base+".png",background=await sharp(media).resize(w,h,{fit:"cover"}).blur(30).modulate({brightness:.46,saturation:.72}).png().toBuffer(),foreground=await sharp(media).resize({width:920,height:820,fit:"inside",withoutEnlargement:false}).png().toBuffer(),meta=await sharp(foreground).metadata(),fw=meta.width||920,fh=meta.height||820,fx=Math.round((w-fw)/2),fy=Math.round(720+(820-fh)/2),lineGap=Math.round(fit.size*1.18),headline=fit.lines.map((x,i)=>`<tspan x="90" dy="${i?lineGap:0}">${esc(x)}</tspan>`).join(""),frameX=Math.max(36,fx-24),frameY=Math.max(620,fy-82),frameW=Math.min(w-72,fw+48),frameH=Math.min(980,fh+126),overlay=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><rect width="${w}" height="${h}" fill="rgba(4,10,24,.28)"/><rect x="0" y="0" width="${w}" height="610" fill="rgba(4,10,24,.50)"/><text x="90" y="190" fill="#93c5fd" font-family="Arial,sans-serif" font-size="26" font-weight="700" letter-spacing="4">MAHGPT • LATEST POST</text><text x="90" y="285" fill="#ffffff" font-family="Arial,sans-serif" font-size="${fit.size}" font-weight="700">${headline}</text><rect x="${frameX}" y="${frameY}" width="${frameW}" height="${frameH}" rx="30" fill="rgba(255,255,255,.97)"/><circle cx="${frameX+47}" cy="${frameY+43}" r="18" fill="#0f172a"/><text x="${frameX+78}" y="${frameY+52}" fill="#111827" font-family="Arial,sans-serif" font-size="28" font-weight="700">MahGPT</text><text x="${frameX+frameW-34}" y="${frameY+50}" text-anchor="end" fill="#64748b" font-family="Arial,sans-serif" font-size="22">Instagram post</text><rect x="58" y="1660" width="964" height="118" rx="32" fill="rgba(15,23,42,.78)" stroke="rgba(255,255,255,.18)"/><text x="540" y="1712" text-anchor="middle" fill="#ffffff" font-family="Arial,sans-serif" font-size="30" font-weight="700">See the full post on Instagram</text><text x="540" y="1752" text-anchor="middle" fill="#bfdbfe" font-family="Arial,sans-serif" font-size="23">mahgpt.com</text></svg>`;await mkdir(pngPath.slice(0,pngPath.lastIndexOf("/")),{recursive:true});await sharp(background).composite([{input:Buffer.from(overlay),top:0,left:0},{input:foreground,top:fy,left:fx}]).png().toFile(pngPath);return pngPath};
