import { readFile, writeFile, mkdir } from "node:fs/promises";
import { cleanHeadline, editorialSummary, storySlug, sourceName, detectPartner } from "./social-content.mjs";

export const FEED="assets/news-feed.json", LINKS="config/social-affiliate-links.json", QUEUE="data/social-queue.json", HISTORY="data/social-delivery-history.json", LEGACY="data/telegram-published.json";
const readJson=async(p,f)=>{try{return JSON.parse(await readFile(p,"utf8"))}catch{return f}};
const localDate=()=>{const p=new Intl.DateTimeFormat("en-US",{timeZone:"Europe/Istanbul",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());return {year:+p.find(x=>x.type==="year").value,month:+p.find(x=>x.type==="month").value,day:+p.find(x=>x.type==="day").value}};
export const slotTimes=(d=localDate())=>[8,10,12,14,16,18,20,22,0,2].map(hour=>{const utcHour=(hour+21)%24, day=hour<3?d.day-1:d.day;return new Date(Date.UTC(d.year,d.month-1,day,utcHour,20)).toISOString()});
const resolve=(partner,links)=>{const e=partner?(links[partner]||{}):{};if(!partner||!e.officialUrl&&!e.affiliateUrl&&!e.redirectPath)return {url:"",status:null};if(e.status==="active"&&e.affiliateUrl)return {url:e.redirectPath||e.affiliateUrl,status:"active"};return {url:e.redirectPath||e.officialUrl||"",status:e.status||"none"}};
const itemPost=(n,links,scheduled,history)=>{const headline=cleanHeadline(n.headline||n.title), partner=detectPartner({...n,headline}), product=resolve(partner,links), id=n.source||[n.title,n.publishedAt].join("|"), old=history.stories?.[id]?.telegram;return {story_id:id,source_url:n.source||"",headline,summary:editorialSummary({...n,headline,detectedPartner:partner}),mahgpt_url:"https://mahgpt.com/news/story.html?id="+encodeURIComponent(storySlug(headline)),image:n.image||"",source_name:sourceName(n.source),detected_partner:partner,product_url:product.url,affiliate_status:product.status,scheduled_publish_at:scheduled,telegram:old?.status==="published"?{status:"skipped_duplicate",published_at:old.published_at||null}:{status:"pending",published_at:null},linkedin:{status:"pending"},instagram:{status:"pending"},x:{status:"pending"}}};
const mergeLegacy=async history=>{const legacy=await readJson(LEGACY,{published:{}});for(const [id,v] of Object.entries(legacy.published||{})){if(v.status==="sent"&&!history.stories[id])history.stories[id]={telegram:{status:"published",published_at:v.sentAt||null},linkedin:{status:"pending"},instagram:{status:"pending"},x:{status:"pending"}}}return history};
export const buildQueue=async()=>{const feed=await readJson(FEED,{items:[]}),links=await readJson(LINKS,{}),history=await mergeLegacy(await readJson(HISTORY,{version:1,stories:{}}));const items=(feed.items||[]).filter(n=>n&&n.title&&n.source).slice(0,10),slots=slotTimes();const queue={version:1,queue_date:new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date()),created_at:new Date().toISOString(),source_feed_updated_at:feed.updatedAt||null,items:items.map((n,i)=>itemPost(n,links,slots[i]||slots.at(-1),history))};await mkdir("data",{recursive:true});await writeFile(HISTORY,JSON.stringify(history,null,2)+"\n");await writeFile(QUEUE,JSON.stringify(queue,null,2)+"\n");console.log("Social queue rebuilt:",queue.items.length,"items");return queue};
if(process.argv[1]?.endsWith("social-queue.mjs"))await buildQueue();
