import { readFile, writeFile, mkdir } from "node:fs/promises";
import { validateSocialPost, validateImageUrl, inferSourceName, cleanHeadline, editorialSummary, storySlug, detectPartner, isRejectedImage } from "./social-content.mjs";
import { createCard, createStoryCard } from "./social-card.mjs";

export const FEED="assets/news-feed.json", LINKS="config/social-affiliate-links.json", QUEUE="data/social-queue.json", HISTORY="data/social-delivery-history.json", INSTAGRAM_HISTORY="data/instagram-delivery-history.json", LEGACY="data/telegram-published.json";
const readJson=async(p,f)=>{try{return JSON.parse(await readFile(p,"utf8"))}catch{return f}};
const localDate=()=>{const p=new Intl.DateTimeFormat("en-US",{timeZone:"Europe/Istanbul",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());return {year:+p.find(x=>x.type==="year").value,month:+p.find(x=>x.type==="month").value,day:+p.find(x=>x.type==="day").value}};
export const slotTimes=(d=localDate())=>{const first=Date.UTC(d.year,d.month-1,d.day,5,20);const slots=Array.from({length:10},(_,i)=>new Date(first+i*2*60*60*1000).toISOString());if(!slots.every((slot,i)=>i===0||slots[i-1]<slot))throw new Error("Social queue slots must be strictly chronological");return slots};
const resolve=(partner,links)=>{const e=partner?(links[partner]||{}):{};if(!partner||!e.officialUrl&&!e.affiliateUrl&&!e.redirectPath)return {url:"",status:null};if(e.status==="active"&&e.affiliateUrl)return {url:e.redirectPath||e.affiliateUrl,status:"active"};return {url:e.redirectPath||e.officialUrl||"",status:e.status||"none"}};
const basePost=(n,links,scheduled,history,instagramHistory={})=>{const headline=cleanHeadline(n.headline||n.title,n),partner=detectPartner({...n,headline}),product=resolve(partner,links),id=n.source||[n.title,n.publishedAt].join("|"),old=history.stories?.[id]?.telegram,oldInstagram=instagramHistory.stories?.[id]?.instagram;return {story_id:id,source_url:n.source||"",headline,summary:editorialSummary({...n,headline,detectedPartner:partner}),source_name:inferSourceName(n)||"News",original_image_url:n.image||"",image_url:"",image_validation:null,image_mode:"fallback_card",mahgpt_url:"https://mahgpt.com/news/story.html?id="+encodeURIComponent(storySlug(headline)),detected_partner:partner,product_url:product.url,affiliate_status:product.status,scheduled_publish_at:scheduled,telegram:old?.status==="published"?{status:"skipped_duplicate",published_at:old.published_at||null}:{status:"pending",published_at:null},linkedin:{status:"pending"},instagram:oldInstagram?.status==="published"?{status:"published",published_at:oldInstagram.published_at||null,message_id:oldInstagram.message_id||null}:{status:"pending"},x:{status:"pending"},fallback_image_landscape:"",fallback_image_instagram:"",fallback_image_story:""}};
const mergeLegacy=async history=>{const legacy=await readJson(LEGACY,{published:{}});for(const [id,v] of Object.entries(legacy.published||{})){if(v.status==="sent"&&!history.stories[id])history.stories[id]={telegram:{status:"published",published_at:v.sentAt||null},linkedin:{status:"pending"},instagram:{status:"pending"},x:{status:"pending"}}}return history};
export const buildQueue=async()=>{const feed=await readJson(FEED,{items:[]}),links=await readJson(LINKS,{}),history=await mergeLegacy(await readJson(HISTORY,{version:1,stories:{}})),instagramHistory=await readJson(INSTAGRAM_HISTORY,{version:1,stories:{}}),date=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date()),items=(feed.items||[]).filter(n=>n&&n.title&&n.source).slice(0,10),slots=slotTimes(),queue={version:1,queue_date:date,created_at:new Date().toISOString(),source_feed_updated_at:feed.updatedAt||null,items:[]};
for(let i=0;i<items.length;i++){const n=items[i],raw=basePost(n,links,slots[i]||slots.at(-1),history,instagramHistory),checked=validateSocialPost(raw),item=checked.post;if(!item.detected_partner)item.product_url="";if(!isRejectedImage(item.original_image_url)){const result=await validateImageUrl(item.original_image_url);item.image_validation=result;if(result.valid){item.image_url=item.original_image_url;item.image_mode="source"}}if(!item.image_url){item.image_mode="fallback_card";item.fallback_image_landscape=await createCard(item,date,"landscape");item.fallback_image_instagram=await createCard(item,date,"instagram")}const preferredStoryMedia=item.image_url||item.fallback_image_instagram||item.fallback_image_landscape;try{item.fallback_image_story=await createStoryCard(item,date,preferredStoryMedia);console.log("Instagram Story card generated:",JSON.stringify({story_id:item.story_id,path:item.fallback_image_story,source:item.image_url?"feed-media":"fallback-card"}))}catch(error){console.warn("Instagram Story card generation fell back:",JSON.stringify({story_id:item.story_id,message:error.message}));try{if(!item.fallback_image_instagram)item.fallback_image_instagram=await createCard(item,date,"instagram");item.fallback_image_story=await createStoryCard(item,date,item.fallback_image_instagram);checked.repairs.push("story-card-fallback")}catch(fallbackError){checked.warnings.push("story-card-generation-failed");console.warn("Instagram Story card generation failed:",JSON.stringify({story_id:item.story_id,message:fallbackError.message}))}}item.quality_gate={valid:checked.valid,warnings:checked.warnings,repairs:checked.repairs};queue.items.push(item)}
await mkdir("data",{recursive:true});await writeFile(HISTORY,JSON.stringify(history,null,2)+"\n");await writeFile(QUEUE,JSON.stringify(queue,null,2)+"\n");console.log("Social queue rebuilt:",queue.items.length,"items");return queue};
if(process.argv[1]?.endsWith("social-queue.mjs"))await buildQueue();
