import { mkdir, readFile, writeFile } from "node:fs/promises";
import sharp from "sharp";

const esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const DISPLAY={adobe:"Adobe",elevenlabs:"ElevenLabs",invideo:"InVideo",hostinger:"Hostinger","hostinger-horizons":"Hostinger Horizons",horizons:"Hostinger Horizons",semrush:"Semrush",surfer:"Surfer",canva:"Canva",heygen:"HeyGen",fliki:"Fliki",pictory:"Pictory",soundraw:"SOUNDRAW",adcreative:"AdCreative.ai"};
const displayName=v=>DISPLAY[String(v||"").toLowerCase()]||String(v||"");
const words=t=>String(t||"").split(/\s+/).filter(Boolean);
const wrap=(text,maxChars,maxLines=4)=>{const out=[],ws=words(text);let line="";for(const word of ws){const next=(line+" "+word).trim();if(line&&next.length>maxChars){out.push(line);line=word}else line=next}if(line)out.push(line);if(out.length<=maxLines)return out;const kept=out.slice(0,maxLines);kept[maxLines-1]=kept[maxLines-1].replace(/\s+\S*$/,"")+"…";return kept};
const fitHeadline=(text,portrait)=>{const width=portrait?860:1040,base=portrait?54:48,min=portrait?34:30;for(let size=base;size>=min;size-=2){const max=Math.max(12,Math.floor(width/(size*.56)));const lines=wrap(text,max,4);if(lines.length<=4&&lines.every(x=>x.length<=max))return {size,lines}}return {size:min,lines:wrap(text,Math.floor(width/(min*.56)),4)}};
const cardPath=(date,storyId,format="landscape")=>"assets/social-cards/"+date+"/"+storyId.replace(/[^a-z0-9-]+/gi,"-").slice(0,80)+"-"+format;
export { cardPath, fitHeadline };
export const createCard=async(post,date,format="landscape")=>{const portrait=format==="instagram",w=portrait?1080:1200,h=portrait?1350:675,fit=fitHeadline(post.headline,portrait),source=post.source_name||"News",partner=displayName(post.detected_partner),base=cardPath(date,post.headline,format),svgPath=base+".svg",pngPath=base+".png",logo=await readFile("assets/brand/mahgpt-logo.svg","base64"),logoHref="data:image/svg+xml;base64,"+logo,headlineY=portrait?300:250,lineGap=Math.round(fit.size*1.22),badgeY=portrait?700:470,headline=fit.lines.map((x,i)=>"<tspan x=\"80\" dy=\""+(i?lineGap:0)+"\">"+esc(x)+"</tspan>").join(""),badge=partner?"<rect x=\"80\" y=\""+badgeY+"\" width=\"240\" height=\"42\" rx=\"21\" fill=\"#38bdf8\"/><text x=\"200\" y=\""+(badgeY+28)+"\" text-anchor=\"middle\" fill=\"#0f172a\" font-family=\"Arial,sans-serif\" font-size=\"20\" font-weight=\"700\">"+esc(partner)+"</text>":"",svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><rect width="${w}" height="${h}" fill="#101827"/><rect x="54" y="38" width="190" height="72" rx="14" fill="#fff"/><image href="${logoHref}" x="66" y="44" width="166" height="60" preserveAspectRatio="xMidYMid meet"/><text x="${w-80}" y="82" text-anchor="end" fill="#93c5fd" font-family="Arial,sans-serif" font-size="24" font-weight="700" letter-spacing="3">AI NEWS</text><text x="80" y="${headlineY}" fill="white" font-family="Arial,sans-serif" font-size="${fit.size}" font-weight="700">${headline}</text>${badge}<text x="80" y="${h-76}" fill="#dbeafe" font-family="Arial,sans-serif" font-size="22">Source: ${esc(source)}</text><text x="${w-80}" y="${h-76}" text-anchor="end" fill="#dbeafe" font-family="Arial,sans-serif" font-size="22">www.mahgpt.com</text></svg>`;await mkdir(svgPath.slice(0,svgPath.lastIndexOf("/")),{recursive:true});await writeFile(svgPath,svg);await sharp(Buffer.from(svg)).png().toFile(pngPath);return pngPath};
